Days/day1.md
Days/day2.md
Days/day3.md

As I was reading through, noticed a couple of things that I thought needed fixed up.
Has been great reading along so far!

(doc) Minor changes to fix typos/links

---

Days/day04.md

This PR correct few ponctuations and focus of the difference of preocupations and show that they are complementary.

Review day04

---

Days/day30.md

- Updated existing **Azure Security Center** section (now **Microsoft Defender for Cloud**)
- Added new **Azure Policy** section
Cheers @MichaelCade

Content updates for day30

---

Days/day58.md

Few changes for Day58

---

Days/day66.md

day66 fix formatting

---

Days/day67.md

day 67 formatting and fixes

---

Days/day07.md

```diff
- even though, even though
+ even though,
```

Removed an extra 'even though'

---

Days/day16.md

Fixed redirection to 404 Page not found when trying to open day14 or day15 file from day16 md file

Fixed broken links of day14 and day15 in day16 md

---

Days/day16.md

Fixed the link to day14.md and day15 which were initially giving 404 page not found

Fix link to day14 and day 15 issue #44

---

Resources.md

This commit has the Resources.md file with all Resource Links from (https://github.com/MichaelCade/90DaysOfDevOps)

Update Resources.md with All Resources Links

---

zh_cn/README.md

Resized main logo to match the default main readme file

Resize main logo

---

Days/day90.md

Corrected some grammar and spelling, dropped post into MS Word for good measure. Added profile links at the end of the post.

Grammar and Spelling (Day90)

---

Days/day89.md

ran through MS Word for good measure too

Fixed some spelling and grammar (Day89)

---

Days/day04.md

Hi, @MichaelCade thanks for releasing this resource. So while reading day04, I noticed there were missing punctuation marks, and some words were not capitalised. This is why I am making this PR. 
Hopefully, there will be a guide in the future on contributing to this project.
PSA: this is my first open-source PR so I may have made some mistakes.

Added punctuation marks and capitalized some words.

---

zh_cn/Days/day01.md

Tried to translate day01 into Chinese.

translate zh_cn day01

---

Days/day48.md
Days/day49.md

In day48 I found a blank list item. 
In day49 I found extra full stops. 
I fixed this

Fixing typos

---

Days/day43.md

changed 'fir education' to 'for education'

a minor typo correction

---

README.md
ja/Days/day01.md
ja/README.md

[ja] translate day01 to Japanese

---

Days/day21.md

Changed the typo on line 60 "redirting" to "redirecting".

typo in day 21 line 60 fixed

---

ja/README.md

[ja] fix broken link for logo

---

Days/day19.md

Update Broken Link

---

Days/day21.md

Repeated word

---

ja/Days/day04.md

[ja] translate day04 to ja

---

Days/day36.md

``` diff
- If I like me you are using Ubuntu or most Linux environments you might find that you already git installed 
+ If you are like me, using Ubuntu or most Linux environments you might find that you already have git installed
```

Corrected the sentence on line 12 of day36

---

ja/Days/day03.md

title: '#90DaysOfDevOps - アプリケーションフォーカス - 3日目'

[ja] translate day03 to ja

---

Days/day70.md

A free edx course produced by 'The Linux Foundation' that explains CI/CD and its practices using Jenkins.

Introduction to Jenkins

---

Days/Linux/create-user.sh
Days/day19.md

Hi there,
I just added userdel command in the create-user script. Please let me know if I could make this kind of changes and create pull request. 
Thanks in advance!

added userdel command in Linux/create-user.sh script

---

Days/day19.md

Hi there,
I did minor correction in the Days/day19.md file.

typo correction at if conditions

---

Days/day52.md

On line 26 and 36 two redirecting links are mistyped.  Now corrected them.

Update day52.md : fixed two redirecting links

---

Days/day04.md

Proposed a grammatical change to 'Target areas'.

Updated day04.md

---

Days/day14.md

Updated day14.md

---

Days/day22.md

Corrected a few errors to make reading easy

Updating Day22.md

---

ja/Days/day01.md
ja/Days/day02.md
ja/Days/day04.md
ja/Days/day05.md

[ja] add day05 and minor change

---

ja/README.md

[ja] update table of contents

---

Days/day51.md

In the Listing Resources table, the last row is repeated

repeated line

---

Days/day52.md
Days/day53.md

Some of the folder links are not working because of the location so I changed them to the correct location.

change the file locations

---

Days/day54.md
Days/day55.md
Days/day58.md
Days/day70.md
Days/day72.md

change the file locations to the correct folder

file location change

---

ja/Days/day06.md
ja/README.md

DevOps - The real stories - Day 6
--> 
DevOps - 本当の話

[ja] add day06

---

Days/day87.md

Change file location

---

Days/day06.md

Made multiple grammar fixes in the day06.md file
Signed-off-by: Abhisman Sarkar <abhismansarkar@pop-os.localdomain>

Grammar fixes

---

Days/day23.md

Clarified the source of the content and added option for consumption by video from the original series - Day 23. Also added a link to a Subnetting series, in case your viewers wanted to go further with Subnetting.

Added Practical Networking links for Day23

---

Days/day22.md

Clarified the source of the content and added option for consumption by video from the original series - Day 22.

Added Practical Networking links for Day22

---

Days/day21.md

Clarified the source of the content and added option for consumption by video from the original series.

Added Practical Networking links and attribution 

---

zh_cn/Days/day37.md

translate zh_cn

---

Days/day14.md

Update day14.md - Spacing issue

---

zh_cn/Days/day10.md

update day10.md 修改字段

---

vi/Days/day01.md
vi/README.md

Hey @MichaelCade, thanks for the awesome resource. 👍🏾 
I am adding Vietnamese translation to it. 🇻🇳 
By the way, can I share the translated resources on https://dev.vntechies.com/ - an open-source learning website for Vietnamese cloud enthusiasts? Of course, we will add the credit and the license appropriately 😄

Added Vietnamese translation + day 1 content

---

ja/Days/day19.md

add ja day19

---

ja/Days/day20.md

add ja day20

---

ja/README.md

add ja index day14-day20

---

ja/Days/day15.md

add ja day15

---

ja/Days/day16.md

add ja day16

---

ja/Days/day17.md

add ja day17

---

ja/Days/day18.md

add ja day18

---

Days/day51.md

Hi, 
I found the blog useful by deploying `minikube` using Vagrant and Ansible. It is obvious that Ansible is not covered from start to `day 51` but this might be useful later come back on it.

added usefull free resource to deploy minikube

---

ja/Days/day26.md

ja - add ja day26

---

ja/Days/day26.md
ja/Days/day27.md

ja - add ja day27

---

ja/Days/day21.md

ja - add ja day21

---

ja/Days/day26.md
ja/README.md

ja - add Index day21 to day27

---

ja/Days/day22.md

ja - add ja day22

---

ja/Days/day23.md

ja - add ja day 23

---

ja/Days/day24.md

ja - add ja day24

---

ja/Days/day25.md

ja - add ja day25

---

Days/day11.md

Updated day11.md

---

pl/day02.md

Hi!
I've starterd the work on translating the next days to polish.
Day02 has been translated so far.

Day02 Polish translation

---

Days/day25.md

Added "." and space. After documentation link on line 67.

Solved Typo

---

es/Days/day06.md

Signed-off-by: Manuel Vergara <manuel@vergaracarmona.es>

Translated to Spanish the day06 file

---

2023/day14.md

`Container Image Scanning` topic, part of `Continuous Build, Integration, Testing (Container & Image scan, DAST, Fuzzing, IAST)` section.
I think this is good enough for the first day of this section.
Do comment if you think otherwise. The next day I will expand that a bit and go into the details of how image scanners work under the hood.

Day 14: Container Image Scanning

---

2023/day16.md

Two things about this:
- I think it turned out to be a bit short (~700 words). @MichaelCade, do you want me to expand this a bit? Maybe with a paragraph about the security context of fuzzing or an example that does not involve unit testing?
- I know that this year's edition uses Python as a programming language. I wrote this in Go because this is what I'm most familiar with. If you want me to I try to adapt this to Python (find a fuzzy testing lib for python and translate the example)
Let me know what you believe is the best thing is to do and I will make the changes.

Add Day 16: Fuzzing

---

2023/day49.md

Just a test PR - will add graphics, verbiage etc as I go

text for day 49 - start of AWS

---

2023.md

- add Anton's name to "Continuous Delivery & Deployment" topic
**NOTE:** My editor slightly reformated the markdown (removed some trailing whitespace and reformated the table.) I think that is the correct way to format markdown, but if you don't like these changes I can revert them and only keep the name change

Add Svetlomir's name to "Continuous Build, Integration, Testing" topic

---

README.md

Added 2 buttons to the README.md:
- Website Link
- GitHub Stars

Added Website and GitHub stars buttons

---

2023/day18.md

Add information for IAST topic, part of Continuous Build, Integration, Testing (Container & Image scan, DAST, Fuzzing, IAST) section.

Add information for IAST

---

README.md

Forgot to include the hyperlinks to both of the buttons in previous PR #271

Added links to the `website` and `GH stars` button

---

2022/Days/day10.md

Changing the description to more elabroate and easy to understand one.

Changing the `go build` description

---

index.html

Added Title "90DaysOfDevOps"
and description "A learning resource for the community to pick up a foundational theory and hands-on knowledge and understanding of the key areas of DevOps. Follow along and join the community!"

Updated title and description for better SEO

---

2022/Days/day11.md

There was a spelling mistake, i corrected it.

Corrected spelling mistake

---

README.md

Added a Link to the website for ease of navigation between the repo and the website

Link for website

---

2023.md
2023/day21.md

This is day 21 - Continuous Image Repository Scan
It builds on the knowledge of Day 14, putting image scanning in the perspective of something that is continuous and automated in the CI/CD pipelines. I am also mentioning different approaches to handling the results that come from the image scanner.

Day 21: Continuous Image Repository Scan

---

2023/day43.md

Added day43.md for Python

---

2023/day42.md
2023/day44.md

3rd day of Python:
- OOP
- Data Structures

Added Day 44 for Python

---

2023.md
2023/day43.md
2023/day44.md
2023/day45.md

Added day 4 of Python:
- Debugging, testing and Regular expression

Added day 45 of Python

---

_sidebar.md

In sidebar there was spelling mistake. That PR fix that.

Fix spelling mistake

---

2023.md
2023/day46.md
2023/day47.md

Added Day 46 & 47 for Python
- Web development in Python
- Automation with Python

Added Day 46 & 47

---

2022/Days/day14.md

for https://github.com/MichaelCade/90DaysOfDevOps/issues/365

docs: introduce alternative virtual environment setup for m1 macOS users

---

2023/day78.md

Update Day78.md to include setting up Service Mesh.
In this module, we install the Istio service mesh, verify functionality and expose and access the application.

Update Day78.md to include setting up Service Mesh

---

.vscode/settings.json
2023/day77.md
2023/day78.md
2023/day79.md
2023/day80.md
2023/day81.md
2023/day82.md
2023/day83.md

Finish Day83 to cover Ambient mesh, update other modules to point to the next day, and add a plug for #70DaysofServiceMesh.
Ambient Mesh is the new Alpha feature of Istio 1.17 that enables a Sidecar-less mode of operations with Istio. 
This is highly advantageous to reduce resource consumption, cost, and even simplify non-disruptive on-boarding for services into a mesh.

Finish Day83 to cover Ambient mesh, update other modules 

---

2022/Days/day34.md

Hi there. The link to the script file was incorrect, I've fixed it, thank you.

Fixed link typo in 2022 day34

---

README.md

- add fork badge
- add issue badge

add: badges in README.md

---

2023/day04.md

docs: correct typos on day 4

---

2022/Days/day84.md

It should be`may be` not `maybe`

Spelling  mistake in day84.md

---

2022/Days/day28.md

As, suggested under #444 , corrected up the issues.
Added up the best rated and reviewed by 4.4M for the AWS content in day 28(2022).

Corrected up the YT link for Aws on day_28

---

2023/day77.md

fixed a typo on day77.md

---

2023.md

Add README link to [Vietnamese version](https://github.com/Cotchi666/90DaysOfDevOps/blob/patch-1/2023.md)

 Add README link to Vietnamese version 2023

---

README.md

- displays total average rating
- clickable so people can easily rate the repo on https://repo-rater.eddiehub.io

RepoRater badge

---

2023/day50.md

After 50day, it is 51day but it was written as the 52day. So I fixed it.

Fix typo on day50 in 2023

---

2024/day27.md

This PR contains all resources needed to follow along with all but the most elaborate demo for my presentation.

Adds resources for day 27

---

2024/day30.md

Created a file for day 30 to upload

upload of day 30 comments

---

2024/day64.md

Adding initial bio and video link w/ preview image. This is a link to my own personal youtube channel as a placeholder until the real 90DoD link is ready 
@MichaelCade : Please replace youtube link when ready, and really make any changes you see fit :) Thanks MC! 
kyler

Update day64.md w/ initial links and content

---

2024/day79.md

Adding some resources and additional material for my presentation.

add resources for day 79

---

2024/day87.md

Added day 87 of 2024: `Hands-on Performance Testing with k6`

Day 87, 2024: `Hands-on Performance Testing with k6`

---

2024/day23.md

Pull request incorporating minor correction in the Docker command documented in file `2024/day23.md`

Minor correction of Docker commands documeted in 2024/day23.md

---

2022/vi/Days/day84.md
2022/vi/Days/day85.md
2022/vi/Days/day86.md
2022/vi/Days/day87.md
2022/vi/Days/day88.md
2022/vi/Days/day89.md
2022/vi/Days/day90.md
2022/vi/README.md

Final PR for Vietnamese translation.
It was a long journey ;)

added vi translation w13

---

2023/vi/days/day01.md
2023/vi/days/day02.md
2023/vi/days/day03.md
2023/vi/days/day04.md
2023/vi/days/day05.md
2023/vi/days/day06.md

It is me again with the 2023 translation :) w1 PR, please review

added w1 vi
